name: Build Java Application

on:
  push:

jobs:
  build-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the code using Maven
        run: mvn package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prasannabavaraju
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: prasanna/myimagejava:latest
          push: true
