name: build java Application
on:
push:
jobs:
 builddeployjob:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install Java and Maven
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven
   - name: Install docker
     uses: docker/setup-buildx-action@v3
   - name: build the code
     run: mvn package
   - name: Loginto Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Build dockerfile and push Image
     uses: docker/build-push-action@v6
     with:
      context: .    # path where dockerfile is- which is curent directory
      tags: sonal04/myimagejava  # name of the image
      push: true

